name: task_managment
description: "Enhance your workflow with a powerful and intuitive task management application built with Flutter. This streamlined solution empowers you to create, organize, and prioritize tasks for maximum efficiency."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0



flutter:

  uses-material-design: true


  assets:
    - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/Roboto/RobotoCondensed-Bold.ttf
        - asset: assets/fonts/Roboto/RobotoCondensed-Italic.ttf
        - asset: assets/fonts/Roboto/RobotoCondensed-Thin.ttf
        - asset: assets/fonts/Roboto/RobotoCondensed-Medium.ttf

